### ISSUE TITLE
The table `main.User` does not exist in the current database.

### ISSUE THREAD

**Issue by micgre0** [nrwl/nx-recipes#83]
Hi, I just downloaded your repository and tried to run nestjs-prisma. While trying to create a user, I encountered the following error:
``The table `main.User` does not exist in the current database.``

Am I the only one affected by this error?

Also probably something is not working with prisma 5.10.2. When you run the serve command the error is as follows:
`Error: Cannot find module 'nx-recipes/nestjs-prisma/node_modules/@prisma/client/one'`

**Comment by micgre0** [comment]
When you check the generated client in node_modules, it turns out that:
- In case of first error, dev.db is empty
- In case of second error, dev.db is not present
